/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125146-gc6bb22dea0-20260621"
#endif /* AVUTIL_FFVERSION_H */
